const DEFAULT_SETTINGS = {
    general: {
        twitchChannel: '',
        clientId: '',
        accessToken: ''
    },
    chat: {
        maxMessages: 15,
        messageLifetimeMs: 20000,
        pillboxBgColor: '#000000',
        pillboxOpacity: 65,
        pillboxRadius: 8,
        pillboxPadding: '8px 12px',
        messageGap: 8,
        userFontFamily: "system-ui, -apple-system, 'Inter', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        userFontSize: 16,
        userFontWeight: 800,
        userFontStyle: 'normal',
        userTextTransform: 'none',
        userLetterSpacing: 0,
        userShadowColor: '#000000',
        userShadowBlur: 3,
        userShadowOffsetX: 1,
        userShadowOffsetY: 1,
        msgFontFamily: "system-ui, -apple-system, 'Inter', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        msgColor: '#f8f8f8',
        msgFontSize: 16,
        msgFontWeight: 500,
        msgFontStyle: 'normal',
        msgLetterSpacing: 0,
        msgShadowColor: '#000000',
        msgShadowBlur: 2,
        msgShadowOffsetX: 1,
        msgShadowOffsetY: 1,
        borderWidth: 0,
        borderStyle: 'solid',
        borderColor: '#ffffff'
    },
    events: {
        fontFamily: "system-ui, -apple-system, 'Montserrat', 'Inter', 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
        fontSize: 20,
        fontWeight: 800,
        fontStyle: 'normal',
        textDecoration: 'none',
        textTransform: 'uppercase',
        kerning: 1,
        textColor: '#ffffff',
        labelColor: '#ff9900',
        shadowColor: '#000000',
        shadowX: 2,
        shadowY: 2,
        shadowBlur: 4,
        layout: 'vertical',
        spacing: 12,
        padding: '5px 10px',
        orientation: 'horizontal',
        labelPosition: 'before',
        bgColor: 'transparent',
        bgOpacity: 0,
        borderRadius: 0,
        borderWidth: 0,
        borderStyle: 'solid',
        borderColor: '#ffffff',
        highlightColor: '#00FF00',
        highlightDurationMs: 2000
    }
};

window.DEFAULT_SETTINGS = DEFAULT_SETTINGS;
